# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 18:01
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170220_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_mob',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=None, default=django.utils.timezone.now, error_messages=set(['no']), max_length=128),
            preserve_default=False,
        ),
    ]
