# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 18:25
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_phone_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_mob',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
